# https://cloud.google.com/kubernetes-engine/docs/tutorials/hello-app?hl=pt-br
# used kompose to convert docker-compose to kubernets
version: "3"
services:
  app:
    build: .
    depends_on:
      - postgres
    ports:
      - "80:3000"
    env_file:
      - .env

  postgres:
    image: postgres:latest
    env_file:
      - .env
    ports:
      - "5432:5432"
